# -*- coding: utf-8 -*-
"""shrink_csv-Done.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JMaTGA-zcReQRuqitQx2f8yh5itQeMn
"""

import pandas as pd
import os

# Tool to help you shrink a XLS or CSV file down to a specified number of rows
def shrink_file(input_file, output_file, row_size):
    # Check if the file exists
    if os.path.exists(input_file):
        # Load the file based on its extension
        if input_file.endswith('.xlsx'):
            df = pd.read_excel(input_file)
        elif input_file.endswith('.csv'):
            df = pd.read_csv(input_file)
        else:
            raise ValueError("Unsupported file format. Please provide a .xlsx or .csv file.")

        # Check if the DataFrame has enough rows
        if len(df) < row_size:
            raise ValueError(f"The file {input_file} contains fewer than {row_size} rows.")
        else:
            # Get random rows from the DataFrame
            df_sampled = df.sample(n=row_size, random_state=1)  # Set random_state for reproducibility

            # Write the DataFrame back to CSV
            df_sampled.to_csv(output_file, index=False)
            print(f"Successfully saved {row_size} rows to {output_file}.")
    else:
        raise ValueError(f"The file {input_file} does not exist.")

# Set file paths and parameters
input_file = '/content/drive/MyDrive/Data/OnlineRetail.xlsx'  # Change this to your input file path (.xlsx or .csv)
output_file = 'OnlineRetail_shrunk.csv'  # Output file name
row_size = 2000  # Desired number of rows

# Call the function
shrink_file(input_file, output_file, row_size)

